sudo: required

language: node_js

services:
  - docker

cache:
  directories:
  - node_modules

node_js:
  - "8"

notifications:
  email:
    - sunnykturo@gmail.com

before_install:
  - docker build -t cicd-test .    

script:
  - npm run lint
  - npm run build
  - npm test